{
  "formatVersion": "1.1",
  "component": {
    "group": "com.thaind.score",
    "module": "score-calculator",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0-RC1"
          }
        }
      ],
      "files": [
        {
          "name": "score-calculator-1.0.2.aar",
          "url": "score-calculator-1.0.2.aar",
          "size": 3076,
          "sha512": "702808834335c96c99c99915dbfcf29e0bd64698ce966f16d9d7fa81f07416ee767e420d133015a9386e7ae0cab08d7a9af5c2e7a48ee8cb365e866c7967632a",
          "sha256": "1ed02eea077e0c03deb666b0b921b0ad8bfac7e679b344cff1c18128d90cddde",
          "sha1": "85cc039e15ceb980f28dd04dcdf513d16bde01eb",
          "md5": "6a32033fab2d14615ccfeef36df69cec"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0-RC1"
          }
        }
      ],
      "files": [
        {
          "name": "score-calculator-1.0.2.aar",
          "url": "score-calculator-1.0.2.aar",
          "size": 3076,
          "sha512": "702808834335c96c99c99915dbfcf29e0bd64698ce966f16d9d7fa81f07416ee767e420d133015a9386e7ae0cab08d7a9af5c2e7a48ee8cb365e866c7967632a",
          "sha256": "1ed02eea077e0c03deb666b0b921b0ad8bfac7e679b344cff1c18128d90cddde",
          "sha1": "85cc039e15ceb980f28dd04dcdf513d16bde01eb",
          "md5": "6a32033fab2d14615ccfeef36df69cec"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "score-calculator-1.0.2-sources.jar",
          "url": "score-calculator-1.0.2-sources.jar",
          "size": 1271,
          "sha512": "a1c640cbb2a40c7d22be224a14def34487027912c96adb6cb30839494d0303d34d748ec17c9f21731c1dfd92c81583fd33b08655b9317edd3212ef18b6aed4b2",
          "sha256": "4b77aab6ad60959120b48910b3c8865cb30ea46763443a2f3662808ebec53f3e",
          "sha1": "dd6ee68b5980eb576aaee5d114074da13c5aa814",
          "md5": "4eea1551c539aa22219daf8ad58e2951"
        }
      ]
    }
  ]
}
